-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  max_teams integer DEFAULT 8,
  min_teams integer DEFAULT 8,
  play_day text CHECK (play_day = ANY (ARRAY['monday'::text, 'tuesday'::text, 'wednesday'::text, 'thursday'::text, 'friday'::text])),
  play_time time without time zone DEFAULT '22:30:00'::time without time zone,
  status text DEFAULT 'registration'::text CHECK (status = ANY (ARRAY['registration'::text, 'pending'::text, 'in_progress'::text, 'completed'::text])),
  registration_deadline timestamp with time zone,
  order integer NOT NULL DEFAULT 99,
  CONSTRAINT categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.courts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  photo_url text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  venue_id uuid,
  CONSTRAINT courts_pkey PRIMARY KEY (id),
  CONSTRAINT courts_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.venues(id)
);
CREATE TABLE public.league_gallery (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  league_id uuid,
  image_url text NOT NULL,
  caption text,
  match_id uuid,
  uploaded_at timestamp with time zone DEFAULT now(),
  uploaded_by uuid,
  CONSTRAINT league_gallery_pkey PRIMARY KEY (id),
  CONSTRAINT league_gallery_league_id_fkey FOREIGN KEY (league_id) REFERENCES public.leagues(id),
  CONSTRAINT league_gallery_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.league_matches(id),
  CONSTRAINT league_gallery_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.league_matches (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  league_id uuid NOT NULL,
  league_team1_id uuid NOT NULL,
  league_team2_id uuid NOT NULL,
  team1_sets1_won integer CHECK (team1_sets1_won >= 0),
  team2_sets1_won integer CHECK (team2_sets1_won >= 0),
  winner_league_team_id uuid,
  match_date timestamp with time zone,
  status text DEFAULT 'SCHEDULED'::text CHECK (status = ANY (ARRAY['SCHEDULED'::text, 'COMPLETED'::text, 'CANCELLED'::text])),
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  walkover boolean DEFAULT false,
  walkover_team_id uuid,
  match_number integer,
  category_id uuid,
  team1_tie1_won integer NOT NULL,
  team2_tie1_won integer,
  team1_sets2_won integer,
  team2_sets2_won integer,
  team1_tie2_won integer,
  team2_tie2_won integer,
  team1_tie3_won integer,
  team2_tie3_won integer,
  court_id uuid,
  venue_id uuid,
  CONSTRAINT league_matches_pkey PRIMARY KEY (id),
  CONSTRAINT league_matches_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT league_matches_walkover_team_id_fkey FOREIGN KEY (walkover_team_id) REFERENCES public.teams(id),
  CONSTRAINT league_matches_winner_league_team_id_fkey FOREIGN KEY (winner_league_team_id) REFERENCES public.league_teams(id),
  CONSTRAINT league_matches_league_team2_id_fkey FOREIGN KEY (league_team2_id) REFERENCES public.league_teams(id),
  CONSTRAINT league_matches_league_team1_id_fkey FOREIGN KEY (league_team1_id) REFERENCES public.league_teams(id),
  CONSTRAINT league_matches_league_id_fkey FOREIGN KEY (league_id) REFERENCES public.leagues(id),
  CONSTRAINT league_matches_court_id_fkey FOREIGN KEY (court_id) REFERENCES public.courts(id),
  CONSTRAINT league_matches_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.venues(id)
);
CREATE TABLE public.league_schedule (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  league_id uuid,
  category_id uuid,
  round_number integer,
  scheduled_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT league_schedule_pkey PRIMARY KEY (id),
  CONSTRAINT league_schedule_league_id_fkey FOREIGN KEY (league_id) REFERENCES public.leagues(id),
  CONSTRAINT league_schedule_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.league_standings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  league_id uuid NOT NULL,
  team_id uuid NOT NULL,
  points integer NOT NULL DEFAULT 0 CHECK (points >= 0),
  wins integer NOT NULL DEFAULT 0 CHECK (wins >= 0),
  losses integer NOT NULL DEFAULT 0 CHECK (losses >= 0),
  sets_won integer NOT NULL DEFAULT 0 CHECK (sets_won >= 0),
  sets_lost integer NOT NULL DEFAULT 0 CHECK (sets_lost >= 0),
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  position integer,
  games_played integer DEFAULT 0,
  games_won integer DEFAULT 0,
  games_lost integer DEFAULT 0,
  sets_difference integer DEFAULT 0,
  sets_in_favor integer DEFAULT 0,
  sets_against integer DEFAULT 0,
  CONSTRAINT league_standings_pkey PRIMARY KEY (id),
  CONSTRAINT league_standings_league_id_fkey FOREIGN KEY (league_id) REFERENCES public.leagues(id),
  CONSTRAINT league_standings_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.league_teams (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  league_id uuid NOT NULL,
  team_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  inscription_paid boolean NOT NULL DEFAULT false,
  alternate_player text,
  CONSTRAINT league_teams_pkey PRIMARY KEY (id),
  CONSTRAINT league_teams_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT league_teams_league_id_fkey FOREIGN KEY (league_id) REFERENCES public.leagues(id)
);
CREATE TABLE public.league_venue_courts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  league_venue_id uuid NOT NULL,
  court_id uuid NOT NULL,
  is_available boolean DEFAULT true,
  priority integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT league_venue_courts_pkey PRIMARY KEY (id),
  CONSTRAINT league_venue_courts_league_venue_id_fkey FOREIGN KEY (league_venue_id) REFERENCES public.league_venues(id),
  CONSTRAINT league_venue_courts_court_id_fkey FOREIGN KEY (court_id) REFERENCES public.courts(id)
);
CREATE TABLE public.league_venues (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  league_id uuid NOT NULL,
  venue_id uuid NOT NULL,
  courts_count integer DEFAULT 0,
  is_primary boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT league_venues_pkey PRIMARY KEY (id),
  CONSTRAINT league_venues_league_id_fkey FOREIGN KEY (league_id) REFERENCES public.leagues(id),
  CONSTRAINT league_venues_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.venues(id)
);
CREATE TABLE public.leagues (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  category_id uuid,
  image_url text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  courts_available integer CHECK (courts_available > 0),
  time_slots jsonb DEFAULT '[]'::jsonb CHECK (jsonb_typeof(time_slots) = 'array'::text AND jsonb_array_length(time_slots) > 0),
  inscription_cost numeric CHECK (inscription_cost >= 0::numeric),
  description text,
  frequency text DEFAULT 'biweekly'::text,
  match_duration_minutes integer DEFAULT 90,
  points_for_win integer DEFAULT 2,
  points_for_loss_with_set integer DEFAULT 1,
  points_for_loss integer DEFAULT 0,
  points_for_walkover integer DEFAULT 2,
  status text,
  team_size integer,
  common_code text,
  venue_id uuid,
  match_times jsonb DEFAULT '["22:30", "23:15"]'::jsonb,
  courts_per_time_slot integer DEFAULT 2,
  league_type text DEFAULT 'round_robin'::text CHECK (league_type = ANY (ARRAY['round_robin'::text, 'knockout'::text, 'groups'::text, 'custom'::text])),
  rounds integer DEFAULT 1 CHECK (rounds >= 1 AND rounds <= 2),
  CONSTRAINT leagues_pkey PRIMARY KEY (id),
  CONSTRAINT leagues_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT leagues_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.venues(id)
);
CREATE TABLE public.matches (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tournament_id uuid,
  home_team_id uuid,
  away_team_id uuid,
  court_id uuid,
  score text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  status text DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'canceled'::text])),
  start_hour integer,
  match_day date,
  round_number integer,
  winner_team_id uuid,
  round integer,
  start_time time without time zone,
  group_id text,
  CONSTRAINT matches_pkey PRIMARY KEY (id),
  CONSTRAINT matches_away_team_id_fkey FOREIGN KEY (away_team_id) REFERENCES public.teams(id),
  CONSTRAINT matches_court_id_fkey FOREIGN KEY (court_id) REFERENCES public.courts(id),
  CONSTRAINT matches_home_team_id_fkey FOREIGN KEY (home_team_id) REFERENCES public.teams(id),
  CONSTRAINT matches_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id),
  CONSTRAINT matches_winner_team_id_fkey FOREIGN KEY (winner_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.professors (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text NOT NULL,
  specializations jsonb NOT NULL DEFAULT '[]'::jsonb,
  experience_years integer DEFAULT 0 CHECK (experience_years >= 0),
  availability_days ARRAY DEFAULT ARRAY['monday'::text, 'tuesday'::text, 'wednesday'::text, 'thursday'::text, 'friday'::text],
  availability_hours text NOT NULL,
  instagram_handle text,
  whatsapp_number text,
  photo_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT professors_pkey PRIMARY KEY (id)
);
CREATE TABLE public.results (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  match_id uuid,
  winner_team_id uuid,
  score text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT results_pkey PRIMARY KEY (id),
  CONSTRAINT results_winner_team_id_fkey FOREIGN KEY (winner_team_id) REFERENCES public.teams(id),
  CONSTRAINT results_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  whatsapp_number character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sponsors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  logo_url text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sponsors_pkey PRIMARY KEY (id)
);
CREATE TABLE public.teams (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  player1_id uuid,
  player2_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT teams_pkey PRIMARY KEY (id),
  CONSTRAINT teams_player2_id_fkey FOREIGN KEY (player2_id) REFERENCES public.users(id),
  CONSTRAINT teams_player1_id_fkey FOREIGN KEY (player1_id) REFERENCES public.users(id)
);
CREATE TABLE public.tournament_groups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tournament_id uuid NOT NULL,
  group_number integer NOT NULL,
  teams jsonb NOT NULL,
  status text DEFAULT 'IN_PROGRESS'::text CHECK (status = ANY (ARRAY['IN_PROGRESS'::text, 'COMPLETED'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  preferred_day text CHECK (preferred_day = ANY (ARRAY['DAY_1'::text, 'DAY_2'::text, 'MIXED'::text])),
  is_homogeneous boolean DEFAULT false,
  CONSTRAINT tournament_groups_pkey PRIMARY KEY (id),
  CONSTRAINT tournament_groups_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id)
);
CREATE TABLE public.tournament_info (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tournament_id uuid NOT NULL,
  first_place_prize text,
  second_place_prize text,
  third_place_prize text,
  description text NOT NULL,
  rules text NOT NULL,
  tournament_location text NOT NULL,
  signup_limit_date date NOT NULL,
  inscription_cost numeric NOT NULL,
  sponsors text,
  tournament_thumbnail text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  tournament_address text NOT NULL,
  tournament_club_name text NOT NULL,
  requires_shirts boolean DEFAULT false,
  CONSTRAINT tournament_info_pkey PRIMARY KEY (id),
  CONSTRAINT tournament_info_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id)
);
CREATE TABLE public.tournament_matches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tournament_id uuid,
  home_team_id uuid,
  away_team_id uuid,
  group_number integer,
  round character varying NOT NULL CHECK (round::text = ANY (ARRAY['group'::character varying::text, 'quarter_final'::character varying::text, 'semi_final'::character varying::text, 'final'::character varying::text])),
  match_number integer,
  match_day date,
  start_time time without time zone,
  court_id uuid,
  team1_sets1_won integer DEFAULT 0,
  team2_sets1_won integer DEFAULT 0,
  team1_sets2_won integer DEFAULT 0,
  team2_sets2_won integer DEFAULT 0,
  team1_tie1_won integer DEFAULT 0,
  team2_tie1_won integer DEFAULT 0,
  team1_tie2_won integer DEFAULT 0,
  team2_tie2_won integer DEFAULT 0,
  team1_tie3_won integer DEFAULT 0,
  team2_tie3_won integer DEFAULT 0,
  winner_team_id uuid,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'scheduled'::character varying::text, 'in_progress'::character varying::text, 'completed'::character varying::text, 'cancelled'::character varying::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  group_id uuid,
  stage character varying NOT NULL CHECK (stage::text = ANY (ARRAY['group'::character varying::text, 'quarter_final'::character varying::text, 'semi_final'::character varying::text, 'final'::character varying::text])),
  bracket_match_id character varying,
  match_order integer,
  elimination_round character varying,
  walkover boolean DEFAULT false,
  walkover_team_id uuid,
  needs_manual boolean DEFAULT false,
  slot_label text,
  tournament_day integer CHECK (tournament_day = ANY (ARRAY[1, 2, 3])),
  venue_id uuid,
  CONSTRAINT tournament_matches_pkey PRIMARY KEY (id),
  CONSTRAINT tournament_matches_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id),
  CONSTRAINT tournament_matches_winner_team_id_fkey FOREIGN KEY (winner_team_id) REFERENCES public.teams(id),
  CONSTRAINT tournament_matches_court_id_fkey FOREIGN KEY (court_id) REFERENCES public.courts(id),
  CONSTRAINT tournament_matches_away_team_id_fkey FOREIGN KEY (away_team_id) REFERENCES public.teams(id),
  CONSTRAINT tournament_matches_home_team_id_fkey FOREIGN KEY (home_team_id) REFERENCES public.teams(id),
  CONSTRAINT tournament_matches_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.tournament_groups(id),
  CONSTRAINT tournament_matches_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.venues(id)
);
CREATE TABLE public.tournament_sponsors (
  tournament_id uuid NOT NULL,
  sponsor_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tournament_sponsors_pkey PRIMARY KEY (tournament_id, sponsor_id),
  CONSTRAINT tournament_sponsors_sponsor_id_fkey FOREIGN KEY (sponsor_id) REFERENCES public.sponsors(id),
  CONSTRAINT tournament_sponsors_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id)
);
CREATE TABLE public.tournament_standings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tournament_id uuid NOT NULL,
  team_id uuid NOT NULL,
  group_id uuid NOT NULL,
  points integer DEFAULT 0,
  matches_played integer DEFAULT 0,
  matches_won integer DEFAULT 0,
  matches_lost integer DEFAULT 0,
  sets_won integer DEFAULT 0,
  sets_lost integer DEFAULT 0,
  games_won integer DEFAULT 0,
  games_lost integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tournament_standings_pkey PRIMARY KEY (id),
  CONSTRAINT tournament_standings_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id),
  CONSTRAINT tournament_standings_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT tournament_standings_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.tournament_groups(id)
);
CREATE TABLE public.tournament_teams (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tournament_id uuid,
  team_id uuid,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'failed'::text])),
  payment_date timestamp with time zone DEFAULT timezone('utc'::text, now()),
  shirt_sizes jsonb DEFAULT '[]'::jsonb CHECK (jsonb_typeof(shirt_sizes) = 'array'::text AND jsonb_array_length(shirt_sizes) >= 0),
  selected_group_slot text,
  unavailable_times jsonb DEFAULT '[]'::jsonb CHECK (jsonb_typeof(unavailable_times) = 'array'::text),
  CONSTRAINT tournament_teams_pkey PRIMARY KEY (id),
  CONSTRAINT tournament_teams_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id),
  CONSTRAINT tournament_teams_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.tournament_venue_courts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tournament_venue_id uuid NOT NULL,
  court_id uuid NOT NULL,
  is_available boolean DEFAULT true,
  priority integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT tournament_venue_courts_pkey PRIMARY KEY (id),
  CONSTRAINT tournament_venue_courts_tournament_venue_id_fkey FOREIGN KEY (tournament_venue_id) REFERENCES public.tournament_venues(id),
  CONSTRAINT tournament_venue_courts_court_id_fkey FOREIGN KEY (court_id) REFERENCES public.courts(id)
);
CREATE TABLE public.tournament_venues (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tournament_id uuid NOT NULL,
  venue_id uuid NOT NULL,
  courts_count integer DEFAULT 0,
  is_primary boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT tournament_venues_pkey PRIMARY KEY (id),
  CONSTRAINT tournament_venues_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id),
  CONSTRAINT tournament_venues_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.venues(id)
);
CREATE TABLE public.tournaments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  category_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  status text DEFAULT 'upcoming'::text CHECK (status = ANY (ARRAY['upcoming'::text, 'in_progress'::text, 'completed'::text])),
  end_date date NOT NULL,
  start_date date NOT NULL,
  courts_available integer CHECK (courts_available IS NULL OR courts_available > 0),
  time_slots jsonb CHECK (time_slots IS NULL OR jsonb_typeof(time_slots) = 'array'::text),
  max_teams integer NOT NULL DEFAULT 9 CHECK (max_teams = ANY (ARRAY[6, 9, 12, 16])),
  tournament_type text NOT NULL DEFAULT 'NINE_PLAYERS'::text,
  group_time_slots jsonb DEFAULT '[]'::jsonb CHECK (jsonb_typeof(group_time_slots) = 'array'::text),
  common_code text,
  match_duration_minutes integer DEFAULT 75,
  venue_id uuid,
  CONSTRAINT tournaments_pkey PRIMARY KEY (id),
  CONSTRAINT tournaments_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT tournaments_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.venues(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email text NOT NULL,
  password text NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  phone text,
  profile_photo text,
  role text DEFAULT 'user'::text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  onboarding_completed boolean DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.venues (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  slug text UNIQUE,
  address text,
  city text,
  state text,
  country text DEFAULT 'Uruguay'::text,
  postal_code text,
  phone text,
  email text,
  description text,
  logo_url text,
  photo_url text,
  latitude numeric,
  longitude numeric,
  timezone text DEFAULT 'America/Montevideo'::text,
  opening_hours jsonb DEFAULT '{}'::jsonb,
  amenities jsonb DEFAULT '[]'::jsonb,
  social_links jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT venues_pkey PRIMARY KEY (id)
);